### ISSUE TITLE
Can not setup youtube music

### ISSUE THREAD

**Issue by droopanu** [sigma67/spotifyplaylist_to_ytmusic#13]
After running the Setup.py I get no firefox request headers:

```
liviu@streamripper:~/GoogleMusic/spotifyplaylist_to_ytmusic$ python3 Setup.py youtube
Please paste the request headers from Firefox and press Ctrl-D to continue:


```
And nothing happens ....

**Comment by droopanu** [comment]
Neverminded! I figured it out that I need to launch a firefox, go to music.youtube.com and manually capture the headers :D

**Comment by sigma67** [comment]
Yes exactly. I should probably be more specific, but didn't expect this project to gain as much attention as it did
