### ISSUE TITLE
Youtube headers make no sense

### ISSUE THREAD

**Issue by Fmstrat** [sigma67/spotifyplaylist_to_ytmusic#20]
The settings.ini file requests a JSON request header, however this is not available as a Copy option. When converting to a JSON format, it then passes them into the YTAPI which expects `\n` characters. Can you provide an example of what a complete `settings.ini` file should look like?

**Comment by Fmstrat** [comment]
Ahh. I see, it's purely a missing part of the instructions. Everything says to put the headers in the `settings.ini` file, and when it says "Paste and then press Control-D" it means paste them into the TERMINAL, not the `settings.ini` file.

**Comment by sigma67** [comment]
Not sure where the misunderstanding occurs, but it says "open your terminal, run setup.py and paste the headers from YouTube Music". I guess it could say "paste into terminal", but that seems apparent from the context
