### ISSUE TITLE
Force originals (Disney)

### ISSUE THREAD

**Issue by minermartijn** [sigma67/spotifyplaylist_to_ytmusic#28]
Dear all,

Was wondering if there is a way to force originals e.g disney.
I'm following an awesome Disney playlist on spotify that updates every now and again.
So i want this app to update my youtube playlist every day.

Now it updates just fine, but some of the disney songs are translated to other languages.
So last week i was singing along with with We dont talk about bruno in Mandarin instead of English.
And also the family Madrigal in Thai.

Is there any way to force the language?
Or is there any way you guys could make it possible?

Link to playlist.
[https://open.spotify.com/playlist/37i9dQZF1DX8C9xQcOrE6T?si=a4edf239ea87447f](url)

**Comment by sigma67** [comment]
There's a language parameter on init: https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.__init__

You set the language for your results in your browser (i.e. set the language for YouTube Music Web in settings) before retrieving the headers for setup from the request. Alternatively, you can change it in the headers directly, but you need to know what you're doing (it's the hl parameter inside the cookie key).

**Comment by minermartijn** [comment]
This?

`language – Optional. Can be used to change the language of returned data. English will be used by default. Available languages can be checked in the ytmusicapi/locales directory.`

Because well its set to English by default, which I dont think works. Because all the songs are available in English, but got Mandarin, Thai and a few others.

**Comment by sigma67** [comment]
Yes, but you  have to set the language in the web interface also.

![grafik](https://user-images.githubusercontent.com/16363825/163669477-3b9b7360-a3e0-438c-9fc7-f07b448e02e6.png)

**Comment by minermartijn** [comment]
Is there another way to force this to be English?
Like i said, i tried your solution.
