### ISSUE TITLE
How to keep YT - Spotify in sync?

### ISSUE THREAD

**Issue by ameeno** [sigma67/spotifyplaylist_to_ytmusic#30]
Some ideas: 

maybe there could be a --all <username> --exportonly  flag,
this should just download the playlists to a sub directory.

I think there should be an import from file/directory method also, which takes the folder names as name inputs but I will add that later (WIll make a pr)

**Comment by sigma67** [comment]
To your title question, I think this goes way beyond the scope of this repo. Feel free to create your own fork for this purpose and link it here for others to see. This is functionality that many commercial tools offer.

Export only is also something you can realize with fairly simple modifications of the code in your own fork. I appreciate the effort but I don't think this is in line with the idea of this repo - to transfer playlists from Spotify to YouTube Music.

**Comment by ameeno** [comment]
Understood. The ultimate issue I am aiming to resolve is the blanket duplication of all playlists when I use the --all flag. The intention is to dump to folder, then import from folder using file name as playlist name and the -u flag. That would enable keeping playlists on both services in sync.

I will keep changes in fork once it is feature complete and propose a another pr when these bits are available.
