### ISSUE TITLE
Trouble setting up the setttings file

### ISSUE THREAD

**Issue by LadyHaywood** [sigma67/spotifyplaylist_to_ytmusic#41]
Not sure where to find the headers as "browse?" doesn't show using chrome nor firefox. I'm also not sure where to find the user id to add in as well.

**Comment by ashprids** [comment]
I had trouble finding them until I disabled all my extensions. Ad blockers + tracking protection might prevent some of them from showing.

**Comment by LadyHaywood** [comment]
I had thought that as well and while more did show, it wasn't the one I needed

**Comment by sigma67** [comment]
The request should show up if you have the network tools open and click on library. It doesn't really matter which request you use, as long as it's a POST request to music.youtube.com/youtubei/v1.
