### ISSUE TITLE
Update playlists without deletion

### ISSUE THREAD

**Issue by Pathrus** [sigma67/spotifyplaylist_to_ytmusic#44]
Hi,

First thanks for your work this is a vert interesting and usefull project.
This is not an issue but more a question on how to modify the code to update a existing playlist without delete all the songs before.

I try to comment the line 178 remove_songs but it doesn't transfert songs anymore. 
Do you know why it doesn't transfert songs or do you have suggestions on what to modify to be able to do that ?

Thanks,
Pierre

**Comment by sigma67** [comment]
Why wouldn't removing l.178 work? It should work just fine if you want to append items instead of replacing the playlist.
